# Generated by Django 4.1.6 on 2023-02-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_rename_create_date_postcomment_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='published_date',
        ),
    ]
