# Generated by Django 4.1.6 on 2023-02-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='emotion',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('pog', 'pog'), ('fun', 'fun')], max_length=20),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='emotion',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('pog', 'pog'), ('fun', 'fun')], max_length=20),
        ),
    ]
