# Generated by Django 4.1.6 on 2023-02-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0010_test_test1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='test_ptr',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Test1',
        ),
    ]
