# Generated by Django 4.1.6 on 2023-02-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_activity_options'),
        ('wall', '0011_remove_test1_test_ptr_delete_test_delete_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReaction',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.activity')),
                ('emotion', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('pog', 'pog'), ('fun', 'fun')], max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.post')),
            ],
            options={
                'abstract': False,
            },
            bases=('social.activity', models.Model),
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.activity')),
                ('content', models.TextField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='wall.activitycomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.post')),
            ],
            options={
                'abstract': False,
            },
            bases=('social.activity', models.Model),
        ),
    ]
