# Generated by Django 4.1.6 on 2023-02-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0012_activityreaction_activitycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreaction',
            name='activity_ptr',
        ),
        migrations.RemoveField(
            model_name='activityreaction',
            name='post',
        ),
        migrations.DeleteModel(
            name='ActivityComment',
        ),
        migrations.DeleteModel(
            name='ActivityReaction',
        ),
    ]
