# Generated by Django 4.1.6 on 2023-02-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('pog', 'pog'), ('fun', 'fun')], max_length=20)),
                ('icon', models.ImageField(upload_to='emotion_icons/')),
            ],
        ),
    ]
