# Generated by Django 4.1.6 on 2023-02-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactionemotion',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon_reactions/'),
        ),
    ]
