# Generated by Django 4.1.6 on 2023-02-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_reactionemotion_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactionemotion',
            name='icon',
        ),
    ]
