# Generated by Django 4.1.6 on 2023-02-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
