# Generated by Django 4.1.6 on 2023-02-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_activity_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
