# Generated by Django 4.1.6 on 2023-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
