# Generated by Django 4.1.6 on 2023-02-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_usernet_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='profile_is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
