# Generated by Django 4.1.6 on 2023-02-08 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_usernet_profile_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernet',
            name='Subscriptions',
        ),
        migrations.AddField(
            model_name='usernet',
            name='followers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
