# Generated by Django 4.1.6 on 2023-02-14 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_user_privacysettings_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
