# Generated by Django 4.1.6 on 2023-02-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_usernet_activity_status_is_hidden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernet',
            old_name='user_is_hiden',
            new_name='user_is_hidden',
        ),
        migrations.AddField(
            model_name='usernet',
            name='personal_information_is_hidden',
            field=models.CharField(choices=[('all', 'all'), ('confirmed', 'confirmed'), ('nobody', 'nobody')], default='all', max_length=20),
        ),
    ]
