# Generated by Django 4.1.6 on 2023-02-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='relation',
            field=models.CharField(choices=[('not confirmed', 'not confirmed'), ('confirmed', 'confirmed')], default='not confirmed', max_length=20),
        ),
    ]
