# Generated by Django 4.1.6 on 2023-02-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_user_is_hiden_usernet_user_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='technology',
            name='url',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
