# Generated by Django 4.1.6 on 2023-02-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_usernet_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernet',
            name='followers',
        ),
    ]
