# Generated by Django 4.1.6 on 2023-02-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_technology_confirmed_technology_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='url',
            field=models.SlugField(max_length=100),
        ),
    ]
